name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: "3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  device_preview: ^1.2.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    -  imagens/
    - imagens/capa_jogos/
    - imagens/icons_type/

  
