// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARlM1QouA1RmU4uRcl4WrRZAKssVdYgDo',
    appId: '1:169461034439:web:40c40dbd555f354076fde2',
    messagingSenderId: '169461034439',
    projectId: 'poke-info-app',
    authDomain: 'poke-info-app.firebaseapp.com',
    storageBucket: 'poke-info-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2QrIFBm8Qg5emTEAy4t5YbkhoC_qJ358',
    appId: '1:169461034439:android:76bc3fe163e56e6876fde2',
    messagingSenderId: '169461034439',
    projectId: 'poke-info-app',
    storageBucket: 'poke-info-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraZMxWL4gaMZpdTsdSf0Z7yD527UgE-Y',
    appId: '1:169461034439:ios:85f8fe7d1148303876fde2',
    messagingSenderId: '169461034439',
    projectId: 'poke-info-app',
    storageBucket: 'poke-info-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAraZMxWL4gaMZpdTsdSf0Z7yD527UgE-Y',
    appId: '1:169461034439:ios:85f8fe7d1148303876fde2',
    messagingSenderId: '169461034439',
    projectId: 'poke-info-app',
    storageBucket: 'poke-info-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
